spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-aql: true
  datasource:
    hikari:
      url: jdbc:h2:file:./testdb
      driver-class-name: org.h2.Driver
      #      username:
      #      password:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior